### ISSUE TITLE
WishboneSlot causing the game to softlock and error on character death

### ISSUE THREAD

**Issue by JTF195** [nearbear/ValheimBepinexMods#1]
Tested with a fresh install of Valheim 0.146.8, BepInExPack_Valheim-5.4.602, WishboneSlot-1.0.0, and CustomSlotItemLib-1.0.1

The error happens upon death when the Wishbone is equipped (by itself or with the belt / other items)
Other combinations of items without Wishbone equipped do not cause the error.

It also seems to prevent the game from spawning a tombstone and dropping items into it.
Upon logging out and back in, the character is respawned naked, but still has all items in their inventory

From the BepInEx log:
```[Error`  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
Stack trace:
System.Collections.Generic.Dictionary`2+KeyCollection+Enumerator[TKey,TValue].MoveNext () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
CustomSlotItemLib.Patches.UnequipAllItemsPostfix (Humanoid& __instance) (at <f72353b3abc74f43872c8edab30c63fd>:0)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::UnequipAllItems>(Humanoid)
Player.CreateTombStone () (at <8e1e443e7dcc46fb93a437d981d93443>:0)
Player.OnDeath () (at <8e1e443e7dcc46fb93a437d981d93443>:0)
Character.CheckDeath () (at <8e1e443e7dcc46fb93a437d981d93443>:0)
Character.FixedUpdate () (at <8e1e443e7dcc46fb93a437d981d93443>:0)
Humanoid.FixedUpdate () (at <8e1e443e7dcc46fb93a437d981d93443>:0)
Player.FixedUpdate () (at <8e1e443e7dcc46fb93a437d981d93443>:0)```

**Comment by nearbear** [comment]
Reproduced and fixed: https://github.com/nearbear/ValheimBepinexMods/commit/95c8f6f953fab4ee20970544f8f3d145b3684144#diff-e2ebd34c91958c3338f7ebc9ce55291b35afd31a4fd49f2f72e79893a3a5af61

Thank you for the report, the fix is included in the 1.0.2 update of CustomSlotItemLib.

**Comment by JTF195** [comment]
I think I had this error pop up again, but I can no longer reproduce it consistently.

**Comment by nearbear** [comment]
Did it softlock your game like with the character death? Not seeing anywhere else that might cause the same error, but I'll keep an eye on my logs.

**Comment by JTF195** [comment]
Yeah, it softlocked on death again. I forgot to grab the error.

I am using [EquipmentAndQuickSlots](https://valheim.thunderstore.io/package/RandyKnapp/EquipmentAndQuickSlots) as well, so that may have an interaction with it, and haven't taken the time to try to reproduce it again in isolation.

I'll report back if I encounter the issue again

**Comment by nearbear** [comment]
Oh, the wishbone slot mod wasn't pointing at the newest version of CustomSlotItemLib. Oops! Fixed in 1.0.1 of the wishbone slot mod.

**Comment by JTF195** [comment]
Still getting softlocks on death even with CustomSlotItemLib-1.0.2 and WishboneSlot-1.0.1

(Tested again with only those two mods enabled and just wishbone equipped)

**Comment by nearbear** [comment]
OK, I was finally able to reproduce it again using my released copies on thunderstore. Apparently my dev changes somehow never made it into CustomSlotItemLib-1.0.2 and I never noticed because I wasn't using the releases to test bugs... Thank you so much for being persistent! 1.0.3 should now contain the fixes.
